HMODULE   GetMyModuleHandle();
HINSTANCE GetMyInstance() ;

#define WLX_SAS_TYPE_EID_INSERT (WLX_SAS_TYPE_MAX_MSFT_VALUE +1)
#define WLX_SAS_TYPE_EID_REMOVE (WLX_SAS_TYPE_MAX_MSFT_VALUE +2)

#define WM_EID_INSERT (WM_USER +1)
#define WM_EID_REMOVE (WM_USER +2)

// Extracts the lower 32-bits of a UINT_PTR sized value
#define LOW32(x) ((UINT)((UINT_PTR)(x) & 0xFFFFFFFF))

#define IDD_WLXDIAPLAYSASNOTICE_DIALOG    1400
#define IDD_WLXLOGGEDOUTSAS_DIALOG        1500
#define IDD_CHANGE_PASSWORD_DIALOG        1700
#define IDD_WLXDISPLAYLOCKEDNOTICE_DIALOG 1900
#define IDD_WLXWKSTALOCKEDSAS_DIALOG      1950
#define IDD_SHUTDOWN_DIALOG				  2200

#define IDC_WLXLOGGEDOUTSAS_USERNAME      1502  
#define IDC_WLXLOGGEDOUTSAS_PASSWORD      1503  
#define IDC_WLXLOGGEDOUTSAS_DOMAIN        1504  
#define IDC_WLXLOGGEDOUTSAS_OK            1  
#define IDC_WLXLOGGEDOUTSAS_CANCEL        2  

#define IDC_WLXWKSTALOCKEDSAS_USERNAME      1953
#define IDC_WLXWKSTALOCKEDSAS_PASSWORD      1954 
#define IDC_WLXWKSTALOCKEDSAS_DOMAIN        1956
#define IDC_WLXWKSTALOCKEDSAS_OK            1  
#define IDC_WLXWKSTALOCKEDSAS_CANCEL        2  